[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
# Allow GasReport tests to write `test/gas_logs/*.txt` reports.
fs_permissions = [{ access = "write", path = "./test/gas_logs" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[lint]
exclude_lints = [
    "unaliased-plain-import",
    "mixed-case-function",
    "screaming-snake-case-const",
    "erc20-unchecked-transfer",
    "asm-keccak256"
]
